LOCAL_HOST = "127.0.0.1"

SERVER_IP = LOCAL_HOST
SERVER_PORT = 54321

CLIENT_WRAPPER_IP = LOCAL_HOST
CLIENT_WRAPPER_PORT = 12345

SERVER_WRAPPER_IP = LOCAL_HOST
SERVER_WRAPPER_PORT = 8080

LOSSY_IP = LOCAL_HOST
LOSSY_PORT = 8000


WINDOW_SIZE = 10
TIMEOUT_IN_MILLISECONDS = 50

SEPARATOR = "\r\n"
